// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuf/dapplink-wallet.proto

package dal_wallet_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_ERROR   ReturnCode = 0
	ReturnCode_SUCCESS ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ReturnCode_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_dapplink_wallet_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_protobuf_dapplink_wallet_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PublicKey) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decimals      uint32                 `protobuf:"varint,1,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenName     string                 `protobuf:"bytes,3,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	CollectAmount string                 `protobuf:"bytes,4,opt,name=collect_amount,json=collectAmount,proto3" json:"collect_amount,omitempty"`
	ColdAmount    string                 `protobuf:"bytes,5,opt,name=cold_amount,json=coldAmount,proto3" json:"cold_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Token) GetCollectAmount() string {
	if x != nil {
		return x.CollectAmount
	}
	return ""
}

func (x *Token) GetColdAmount() string {
	if x != nil {
		return x.ColdAmount
	}
	return ""
}

type BusinessRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,3,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterRequest) Reset() {
	*x = BusinessRegisterRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterRequest) ProtoMessage() {}

func (x *BusinessRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterRequest.ProtoReflect.Descriptor instead.
func (*BusinessRegisterRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *BusinessRegisterRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *BusinessRegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BusinessRegisterRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

type BusinessRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=Code,proto3,enum=syncs.ReturnCode" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterResponse) Reset() {
	*x = BusinessRegisterResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterResponse) ProtoMessage() {}

func (x *BusinessRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterResponse.ProtoReflect.Descriptor instead.
func (*BusinessRegisterResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *BusinessRegisterResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *BusinessRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ExportAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PublicKeys    []*PublicKey           `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressesRequest) Reset() {
	*x = ExportAddressesRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressesRequest) ProtoMessage() {}

func (x *ExportAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressesRequest.ProtoReflect.Descriptor instead.
func (*ExportAddressesRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ExportAddressesRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *ExportAddressesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExportAddressesRequest) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type ExportAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=Code,proto3,enum=syncs.ReturnCode" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressesResponse) Reset() {
	*x = ExportAddressesResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressesResponse) ProtoMessage() {}

func (x *ExportAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressesResponse.ProtoReflect.Descriptor instead.
func (*ExportAddressesResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *ExportAddressesResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *ExportAddressesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Transactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	From            string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value           string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	TxType          string                 `protobuf:"bytes,5,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transactions) Reset() {
	*x = Transactions{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactions) ProtoMessage() {}

func (x *Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactions.ProtoReflect.Descriptor instead.
func (*Transactions) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *Transactions) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *Transactions) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transactions) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transactions) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transactions) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

type UnSignWithdrawTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Txn           []*Transactions        `protobuf:"bytes,3,rep,name=txn,proto3" json:"txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSignWithdrawTransactionRequest) Reset() {
	*x = UnSignWithdrawTransactionRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSignWithdrawTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSignWithdrawTransactionRequest) ProtoMessage() {}

func (x *UnSignWithdrawTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSignWithdrawTransactionRequest.ProtoReflect.Descriptor instead.
func (*UnSignWithdrawTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *UnSignWithdrawTransactionRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *UnSignWithdrawTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnSignWithdrawTransactionRequest) GetTxn() []*Transactions {
	if x != nil {
		return x.Txn
	}
	return nil
}

type ReturnTransactionHashes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	UnSignTx        string                 `protobuf:"bytes,2,opt,name=un_sign_tx,json=unSignTx,proto3" json:"un_sign_tx,omitempty"`
	TxData          string                 `protobuf:"bytes,3,opt,name=tx_data,json=txData,proto3" json:"tx_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReturnTransactionHashes) Reset() {
	*x = ReturnTransactionHashes{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnTransactionHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnTransactionHashes) ProtoMessage() {}

func (x *ReturnTransactionHashes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnTransactionHashes.ProtoReflect.Descriptor instead.
func (*ReturnTransactionHashes) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ReturnTransactionHashes) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *ReturnTransactionHashes) GetUnSignTx() string {
	if x != nil {
		return x.UnSignTx
	}
	return ""
}

func (x *ReturnTransactionHashes) GetTxData() string {
	if x != nil {
		return x.TxData
	}
	return ""
}

type UnSignWithdrawTransactionResponse struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Code           ReturnCode                 `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg            string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ReturnTxHashes []*ReturnTransactionHashes `protobuf:"bytes,3,rep,name=return_tx_hashes,json=returnTxHashes,proto3" json:"return_tx_hashes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnSignWithdrawTransactionResponse) Reset() {
	*x = UnSignWithdrawTransactionResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSignWithdrawTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSignWithdrawTransactionResponse) ProtoMessage() {}

func (x *UnSignWithdrawTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSignWithdrawTransactionResponse.ProtoReflect.Descriptor instead.
func (*UnSignWithdrawTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *UnSignWithdrawTransactionResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *UnSignWithdrawTransactionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UnSignWithdrawTransactionResponse) GetReturnTxHashes() []*ReturnTransactionHashes {
	if x != nil {
		return x.ReturnTxHashes
	}
	return nil
}

type SignedTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	Signature       string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TxData          string                 `protobuf:"bytes,3,opt,name=tx_data,json=txData,proto3" json:"tx_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignedTransactions) Reset() {
	*x = SignedTransactions{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactions) ProtoMessage() {}

func (x *SignedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactions.ProtoReflect.Descriptor instead.
func (*SignedTransactions) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *SignedTransactions) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *SignedTransactions) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedTransactions) GetTxData() string {
	if x != nil {
		return x.TxData
	}
	return ""
}

type SignedWithdrawTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SignTxn       []*SignedTransactions  `protobuf:"bytes,3,rep,name=sign_txn,json=signTxn,proto3" json:"sign_txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedWithdrawTransactionRequest) Reset() {
	*x = SignedWithdrawTransactionRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedWithdrawTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedWithdrawTransactionRequest) ProtoMessage() {}

func (x *SignedWithdrawTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedWithdrawTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignedWithdrawTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *SignedWithdrawTransactionRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *SignedWithdrawTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignedWithdrawTransactionRequest) GetSignTxn() []*SignedTransactions {
	if x != nil {
		return x.SignTxn
	}
	return nil
}

type ReturnSignedTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	SignedTx        string                 `protobuf:"bytes,2,opt,name=signed_tx,json=signedTx,proto3" json:"signed_tx,omitempty"`
	TxId            string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReturnSignedTransactions) Reset() {
	*x = ReturnSignedTransactions{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnSignedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnSignedTransactions) ProtoMessage() {}

func (x *ReturnSignedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnSignedTransactions.ProtoReflect.Descriptor instead.
func (*ReturnSignedTransactions) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnSignedTransactions) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *ReturnSignedTransactions) GetSignedTx() string {
	if x != nil {
		return x.SignedTx
	}
	return ""
}

func (x *ReturnSignedTransactions) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type SignedWithdrawTransactionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          ReturnCode                  `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ReturnSignTxn []*ReturnSignedTransactions `protobuf:"bytes,3,rep,name=return_sign_txn,json=returnSignTxn,proto3" json:"return_sign_txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedWithdrawTransactionResponse) Reset() {
	*x = SignedWithdrawTransactionResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedWithdrawTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedWithdrawTransactionResponse) ProtoMessage() {}

func (x *SignedWithdrawTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedWithdrawTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignedWithdrawTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *SignedWithdrawTransactionResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *SignedWithdrawTransactionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SignedWithdrawTransactionResponse) GetReturnSignTxn() []*ReturnSignedTransactions {
	if x != nil {
		return x.ReturnSignTxn
	}
	return nil
}

type Withdraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Fee           string                 `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Withdraw) Reset() {
	*x = Withdraw{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdraw) ProtoMessage() {}

func (x *Withdraw) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdraw.ProtoReflect.Descriptor instead.
func (*Withdraw) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *Withdraw) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Withdraw) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Withdraw) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Withdraw) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type SubmitWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WithdrawList  []*Withdraw            `protobuf:"bytes,3,rep,name=withdraw_list,json=withdrawList,proto3" json:"withdraw_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWithdrawRequest) Reset() {
	*x = SubmitWithdrawRequest{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWithdrawRequest) ProtoMessage() {}

func (x *SubmitWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWithdrawRequest.ProtoReflect.Descriptor instead.
func (*SubmitWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitWithdrawRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *SubmitWithdrawRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitWithdrawRequest) GetWithdrawList() []*Withdraw {
	if x != nil {
		return x.WithdrawList
	}
	return nil
}

type SubmitWithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWithdrawResponse) Reset() {
	*x = SubmitWithdrawResponse{}
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWithdrawResponse) ProtoMessage() {}

func (x *SubmitWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWithdrawResponse.ProtoReflect.Descriptor instead.
func (*SubmitWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitWithdrawResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *SubmitWithdrawResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protobuf_dapplink_wallet_proto protoreflect.FileDescriptor

const file_protobuf_dapplink_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/dapplink-wallet.proto\x12\x05syncs\"V\n" +
	"\tPublicKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"7\n" +
	"\aAddress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xa4\x01\n" +
	"\x05Token\x12\x1a\n" +
	"\bdecimals\x18\x01 \x01(\rR\bdecimals\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x03 \x01(\tR\ttokenName\x12%\n" +
	"\x0ecollect_amount\x18\x04 \x01(\tR\rcollectAmount\x12\x1f\n" +
	"\vcold_amount\x18\x05 \x01(\tR\n" +
	"coldAmount\"~\n" +
	"\x17BusinessRegisterRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x03 \x01(\tR\tnotifyUrl\"S\n" +
	"\x18BusinessRegisterResponse\x12%\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x91\x01\n" +
	"\x16ExportAddressesRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x121\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x10.syncs.PublicKeyR\n" +
	"publicKeys\"\x80\x01\n" +
	"\x17ExportAddressesResponse\x12%\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04Code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\taddresses\x18\x03 \x03(\v2\x0e.syncs.AddressR\taddresses\"\x8c\x01\n" +
	"\fTransactions\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x17\n" +
	"\atx_type\x18\x05 \x01(\tR\x06txType\"\x8f\x01\n" +
	" UnSignWithdrawTransactionRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12%\n" +
	"\x03txn\x18\x03 \x03(\v2\x13.syncs.TransactionsR\x03txn\"{\n" +
	"\x17ReturnTransactionHashes\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\x12\x1c\n" +
	"\n" +
	"un_sign_tx\x18\x02 \x01(\tR\bunSignTx\x12\x17\n" +
	"\atx_data\x18\x03 \x01(\tR\x06txData\"\xa6\x01\n" +
	"!UnSignWithdrawTransactionResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12H\n" +
	"\x10return_tx_hashes\x18\x03 \x03(\v2\x1e.syncs.ReturnTransactionHashesR\x0ereturnTxHashes\"v\n" +
	"\x12SignedTransactions\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x17\n" +
	"\atx_data\x18\x03 \x01(\tR\x06txData\"\x9e\x01\n" +
	" SignedWithdrawTransactionRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x124\n" +
	"\bsign_txn\x18\x03 \x03(\v2\x19.syncs.SignedTransactionsR\asignTxn\"w\n" +
	"\x18ReturnSignedTransactions\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\x12\x1b\n" +
	"\tsigned_tx\x18\x02 \x01(\tR\bsignedTx\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"\xa5\x01\n" +
	"!SignedWithdrawTransactionResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12G\n" +
	"\x0freturn_sign_txn\x18\x03 \x03(\v2\x1f.syncs.ReturnSignedTransactionsR\rreturnSignTxn\"g\n" +
	"\bWithdraw\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\tR\x03fee\"\x93\x01\n" +
	"\x15SubmitWithdrawRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x124\n" +
	"\rwithdraw_list\x18\x03 \x03(\v2\x0f.syncs.WithdrawR\fwithdrawList\"Q\n" +
	"\x16SubmitWithdrawResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*$\n" +
	"\n" +
	"ReturnCode\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x012\x82\x04\n" +
	"\x1aBusinessMiddleWireServices\x12U\n" +
	"\x10businessRegister\x12\x1e.syncs.BusinessRegisterRequest\x1a\x1f.syncs.BusinessRegisterResponse\"\x00\x12^\n" +
	"\x1bexportAddressesByPublicKeys\x12\x1d.syncs.ExportAddressesRequest\x1a\x1e.syncs.ExportAddressesResponse\"\x00\x12m\n" +
	"\x16buildUnSignTransaction\x12'.syncs.UnSignWithdrawTransactionRequest\x1a(.syncs.UnSignWithdrawTransactionResponse\"\x00\x12m\n" +
	"\x16buildSignedTransaction\x12'.syncs.SignedWithdrawTransactionRequest\x1a(.syncs.SignedWithdrawTransactionResponse\"\x00\x12O\n" +
	"\x0esubmitWithdraw\x12\x1c.syncs.SubmitWithdrawRequest\x1a\x1d.syncs.SubmitWithdrawResponse\"\x00B\x1aZ\x18./protobuf/dal-wallet-gob\x06proto3"

var (
	file_protobuf_dapplink_wallet_proto_rawDescOnce sync.Once
	file_protobuf_dapplink_wallet_proto_rawDescData []byte
)

func file_protobuf_dapplink_wallet_proto_rawDescGZIP() []byte {
	file_protobuf_dapplink_wallet_proto_rawDescOnce.Do(func() {
		file_protobuf_dapplink_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_dapplink_wallet_proto_rawDesc), len(file_protobuf_dapplink_wallet_proto_rawDesc)))
	})
	return file_protobuf_dapplink_wallet_proto_rawDescData
}

var file_protobuf_dapplink_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_dapplink_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protobuf_dapplink_wallet_proto_goTypes = []any{
	(ReturnCode)(0),                           // 0: syncs.ReturnCode
	(*PublicKey)(nil),                         // 1: syncs.PublicKey
	(*Address)(nil),                           // 2: syncs.Address
	(*Token)(nil),                             // 3: syncs.Token
	(*BusinessRegisterRequest)(nil),           // 4: syncs.BusinessRegisterRequest
	(*BusinessRegisterResponse)(nil),          // 5: syncs.BusinessRegisterResponse
	(*ExportAddressesRequest)(nil),            // 6: syncs.ExportAddressesRequest
	(*ExportAddressesResponse)(nil),           // 7: syncs.ExportAddressesResponse
	(*Transactions)(nil),                      // 8: syncs.Transactions
	(*UnSignWithdrawTransactionRequest)(nil),  // 9: syncs.UnSignWithdrawTransactionRequest
	(*ReturnTransactionHashes)(nil),           // 10: syncs.ReturnTransactionHashes
	(*UnSignWithdrawTransactionResponse)(nil), // 11: syncs.UnSignWithdrawTransactionResponse
	(*SignedTransactions)(nil),                // 12: syncs.SignedTransactions
	(*SignedWithdrawTransactionRequest)(nil),  // 13: syncs.SignedWithdrawTransactionRequest
	(*ReturnSignedTransactions)(nil),          // 14: syncs.ReturnSignedTransactions
	(*SignedWithdrawTransactionResponse)(nil), // 15: syncs.SignedWithdrawTransactionResponse
	(*Withdraw)(nil),                          // 16: syncs.Withdraw
	(*SubmitWithdrawRequest)(nil),             // 17: syncs.SubmitWithdrawRequest
	(*SubmitWithdrawResponse)(nil),            // 18: syncs.SubmitWithdrawResponse
}
var file_protobuf_dapplink_wallet_proto_depIdxs = []int32{
	0,  // 0: syncs.BusinessRegisterResponse.Code:type_name -> syncs.ReturnCode
	1,  // 1: syncs.ExportAddressesRequest.public_keys:type_name -> syncs.PublicKey
	0,  // 2: syncs.ExportAddressesResponse.Code:type_name -> syncs.ReturnCode
	2,  // 3: syncs.ExportAddressesResponse.addresses:type_name -> syncs.Address
	8,  // 4: syncs.UnSignWithdrawTransactionRequest.txn:type_name -> syncs.Transactions
	0,  // 5: syncs.UnSignWithdrawTransactionResponse.code:type_name -> syncs.ReturnCode
	10, // 6: syncs.UnSignWithdrawTransactionResponse.return_tx_hashes:type_name -> syncs.ReturnTransactionHashes
	12, // 7: syncs.SignedWithdrawTransactionRequest.sign_txn:type_name -> syncs.SignedTransactions
	0,  // 8: syncs.SignedWithdrawTransactionResponse.code:type_name -> syncs.ReturnCode
	14, // 9: syncs.SignedWithdrawTransactionResponse.return_sign_txn:type_name -> syncs.ReturnSignedTransactions
	16, // 10: syncs.SubmitWithdrawRequest.withdraw_list:type_name -> syncs.Withdraw
	0,  // 11: syncs.SubmitWithdrawResponse.code:type_name -> syncs.ReturnCode
	4,  // 12: syncs.BusinessMiddleWireServices.businessRegister:input_type -> syncs.BusinessRegisterRequest
	6,  // 13: syncs.BusinessMiddleWireServices.exportAddressesByPublicKeys:input_type -> syncs.ExportAddressesRequest
	9,  // 14: syncs.BusinessMiddleWireServices.buildUnSignTransaction:input_type -> syncs.UnSignWithdrawTransactionRequest
	13, // 15: syncs.BusinessMiddleWireServices.buildSignedTransaction:input_type -> syncs.SignedWithdrawTransactionRequest
	17, // 16: syncs.BusinessMiddleWireServices.submitWithdraw:input_type -> syncs.SubmitWithdrawRequest
	5,  // 17: syncs.BusinessMiddleWireServices.businessRegister:output_type -> syncs.BusinessRegisterResponse
	7,  // 18: syncs.BusinessMiddleWireServices.exportAddressesByPublicKeys:output_type -> syncs.ExportAddressesResponse
	11, // 19: syncs.BusinessMiddleWireServices.buildUnSignTransaction:output_type -> syncs.UnSignWithdrawTransactionResponse
	15, // 20: syncs.BusinessMiddleWireServices.buildSignedTransaction:output_type -> syncs.SignedWithdrawTransactionResponse
	18, // 21: syncs.BusinessMiddleWireServices.submitWithdraw:output_type -> syncs.SubmitWithdrawResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protobuf_dapplink_wallet_proto_init() }
func file_protobuf_dapplink_wallet_proto_init() {
	if File_protobuf_dapplink_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_dapplink_wallet_proto_rawDesc), len(file_protobuf_dapplink_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_dapplink_wallet_proto_goTypes,
		DependencyIndexes: file_protobuf_dapplink_wallet_proto_depIdxs,
		EnumInfos:         file_protobuf_dapplink_wallet_proto_enumTypes,
		MessageInfos:      file_protobuf_dapplink_wallet_proto_msgTypes,
	}.Build()
	File_protobuf_dapplink_wallet_proto = out.File
	file_protobuf_dapplink_wallet_proto_goTypes = nil
	file_protobuf_dapplink_wallet_proto_depIdxs = nil
}
